Update to 2.2 build.sdt.
Doesn't compile:

play-example-form] $ compile
[info] Compiling 10 Scala sources and 8 Java sources to
/Users/johnson/projecthosting/github/play-example-form/target/scala-2.10
/classes...
[error]
/Users/johnson/projecthosting/github/play-example-form/conf/routes:11:
object WebJarAssets is not a member of package controllers
[error] GET     /webjars/*file
controllers.WebJarAssets.at(file)
[error]
/Users/johnson/projecthosting/github/play-example-form/conf/routes:11:
object WebJarAssets is not a member of package controllers
[error] GET     /webjars/*file
controllers.WebJarAssets.at(file)
[error]
/Users/johnson/projecthosting/github/play-example-form/app/views/main.sc
ala.html:7: not found: value WebJarAssets
[error]     <link rel="stylesheet" media="screen"
href="@routes.WebJarAssets.at(WebJarAssets.locate("bootstrap.min.css"))"
>
[error]
        ^
[error] three errors found
[error] (compile:compile) Compilation failed
[error] Total time: 4 s, completed Oct 9, 2013 9:43:18 AM